CREATE DATABASE MEDIA;

USE MEDIA;

CREATE TABLE NOTAS(
    IDNOTAS INT PRIMARY KEY AUTO_INCREMENT,
    INGREDIENTES VARCHAR(30)
);

DROP TABLE NOTAS;

INSERT INTO NOTAS VALUES(NULL, "TESTE");

SELECT * FROM NOTAS;
